# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20190729_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Welcome to the world of coding!'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='tumaa'),
        ),
    ]
